# fly.toml app configuration file generated for name-tester-app on 2025-08-16T21:05:18+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'name-tester-app'
primary_region = 'lhr'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = '512mb'

[deploy]
release_command = "npx prisma migrate deploy"
